const cod_packages = [
    {
        id: 1,
        name: 'Call of Dragon Bot vip 1 (1 ngày)',
        price: '3.69$',
        description_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-auto-bot-vip-1-1.png',
        thumbnail_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-Auto-Bot-P.png',
        is_reduce: false,
        reduced_price: '',
        is_popular: true,
        vip_type: '1',
        created_date: '2024-14-08',
    },
    {
        id: 2,
        name: 'Call of Dragon Bot vip 1 (7 ngày)',
        price: '5.54$',
        description_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-auto-bot-vip-1-1.png',
        thumbnail_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-Auto-Bot-P.png',
        is_reduce: false,
        reduced_price: '',
        is_popular: false,
        vip_type: '1',
        created_date: '2024-13-08',
    },
    {
        id: 3,
        name: 'Call of Dragon Bot vip 1 (30 ngày)',
        price: '13.24$',
        description_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-auto-bot-vip-1-1.png',
        thumbnail_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-Auto-Bot-P.png',
        is_reduce: false,
        reduced_price: '',
        is_popular: true,
        vip_type: '1',
        created_date: '2024-15-08',
    },
    {
        id: 4,
        name: 'Call of Dragon Bot farm gem vip 2 (1 ngày)',
        price: '7.38$',
        description_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-auto-bot-vip-2-1.png',
        thumbnail_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-Auto-Bot-P.png',
        is_reduce: false,
        reduced_price: '',
        is_popular: true,
        vip_type: '2',
        created_date: '2024-16-08',
    },
    {
        id: 5,
        name: 'Call of Dragon Bot farm gem vip 2 (7 ngày)',
        price: '11.07$',
        description_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-auto-bot-vip-2-1.png',
        thumbnail_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-Auto-Bot-P.png',
        is_reduce: false,
        reduced_price: '',
        is_popular: false,
        vip_type: '2',
        created_date: '2024-14-08',
    },
    {
        id: 6,
        name: 'Call of Dragon Bot farm gem vip 2 (30 ngày)',
        price: '26.07$',
        description_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-auto-bot-vip-2-1.png',
        thumbnail_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-Auto-Bot-sale.png',
        is_reduce: true,
        reduced_price: '20.46$',
        is_popular: true,
        vip_type: '2',
        created_date: '2024-17-08',
    },
    {
        id: 7,
        name: 'Call of Dragon Bot farm gem vip 3 (1 ngày)',
        price: '11.79$',
        description_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-auto-bot-vip-3-1.png',
        thumbnail_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-Auto-Bot-sale-bh.png',
        is_reduce: false,
        reduced_price: '',
        is_popular: false,
        vip_type: '3',
        created_date: '2024-18-08',
    },
    {
        id: 8,
        name: 'Call of Dragon Bot farm gem vip 3 (7 ngày)',
        price: '19.49$',
        description_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-auto-bot-vip-3-1.png',
        thumbnail_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-Auto-Bot-sale-bh.png',
        is_reduce: false,
        reduced_price: '',
        is_popular: false,
        vip_type: '3',
        created_date: '2024-16-08',
    },
    {
        id: 9,
        name: 'Call of Dragon Bot farm gem vip 3 (30 ngày)',
        price: '35.70$',
        description_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-auto-bot-vip-3-1.png',
        thumbnail_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-Auto-Bot-sale-bh.png',
        is_reduce: false,
        reduced_price: '',
        is_popular: false,
        vip_type: '3',
        created_date: '2024-18-08',
    },
    {
        id: 10,
        name: 'Call of Dragon Bot farm gem vip SLEEP 30 ngày',
        price: '17.25$',
        description_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-auto-bot-vip-2-1.png',
        thumbnail_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-Auto-Bot-sale.png',
        is_reduce: true,
        reduced_price: '15.64$',
        is_popular: false,
        vip_type: '2',
        created_date: '2024-15-08',
    },
]

export default cod_packages;
