const packages = [
    {
        id: 1,
        name: 'Rise of Kingdom Bot vip 1 (1 ngày)',
        price: '92.000đ',
        description_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-auto-bot-vip-1-1.png',
        thumbnail_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-Auto-Bot-P.png',
        is_reduce: false,
        reduced_price: '',
        is_popular: true,
        vip_type: '1',
        created_date: '2024-14-08',
    },
    {
        id: 2,
        name: 'Rise of Kingdom Bot vip 1 (7 ngày)',
        price: '138.000đ',
        description_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-auto-bot-vip-1-1.png',
        thumbnail_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-Auto-Bot-P.png',
        is_reduce: false,
        reduced_price: '',
        is_popular: false,
        vip_type: '1',
        created_date: '2024-13-08',
    },
    {
        id: 3,
        name: 'Rise of Kingdom Bot vip 1 (30 ngày)',
        price: '330.000đ',
        description_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-auto-bot-vip-1-1.png',
        thumbnail_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-Auto-Bot-P.png',
        is_reduce: false,
        reduced_price: '',
        is_popular: true,
        vip_type: '1',
        created_date: '2024-15-08',
    },
    {
        id: 4,
        name: 'Rise of Kingdom Bot farm gem vip 2 (1 ngày)',
        price: '184.000đ',
        description_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-auto-bot-vip-2-1.png',
        thumbnail_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-Auto-Bot-P.png',
        is_reduce: false,
        reduced_price: '',
        is_popular: true,
        vip_type: '2',
        created_date: '2024-16-08',
    },
    {
        id: 5,
        name: 'Rise of Kingdom Bot farm gem vip 2 (7 ngày)',
        price: '276.000đ',
        description_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-auto-bot-vip-2-1.png',
        thumbnail_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-Auto-Bot-P.png',
        is_reduce: false,
        reduced_price: '',
        is_popular: false,
        vip_type: '2',
        created_date: '2024-14-08',
    },
    {
        id: 6,
        name: 'Rise of Kingdom Bot farm gem vip 2 (30 ngày)',
        price: '650.000đ',
        description_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-auto-bot-vip-2-1.png',
        thumbnail_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-Auto-Bot-sale.png',
        is_reduce: true,
        reduced_price: '510.000đ',
        is_popular: true,
        vip_type: '2',
        created_date: '2024-17-08',
    },
    {
        id: 7,
        name: 'Rise of Kingdom Bot farm gem vip 3 (1 ngày)',
        price: '294.000đ',
        description_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-auto-bot-vip-3-1.png',
        thumbnail_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-Auto-Bot-sale-bh.png',
        is_reduce: false,
        reduced_price: '',
        is_popular: false,
        vip_type: '3',
        created_date: '2024-18-08',
    },
    {
        id: 8,
        name: 'Rise of Kingdom Bot farm gem vip 3 (7 ngày)',
        price: '486.000đ',
        description_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-auto-bot-vip-3-1.png',
        thumbnail_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-Auto-Bot-sale-bh.png',
        is_reduce: false,
        reduced_price: '',
        is_popular: false,
        vip_type: '3',
        created_date: '2024-16-08',
    },
    {
        id: 9,
        name: 'Rise of Kingdom Bot farm gem vip 3 (30 ngày)',
        price: '890.000đ',
        description_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-auto-bot-vip-3-1.png',
        thumbnail_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-Auto-Bot-sale-bh.png',
        is_reduce: false,
        reduced_price: '',
        is_popular: false,
        vip_type: '3',
        created_date: '2024-18-08',
    },
    {
        id: 10,
        name: 'Rise of Kingdom Bot farm gem vip SLEEP 30 ngày',
        price: '430.000đ',
        description_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-auto-bot-vip-2-1.png',
        thumbnail_img: 'https://kamiautobot.com/wp-content/uploads/2024/07/Kami-Auto-Bot-sale.png',
        is_reduce: true,
        reduced_price: '390.000đ',
        is_popular: false,
        vip_type: '2',
        created_date: '2024-15-08',
    },
]

export default packages;
